window.EMMA_MEALS = [
  {
    night: 1, date: "Thu 1 Oct", title: "Ghost Hot Cocoa", emoji: "👻",
    type: "drink", vibe: "cozy",
    hook: "your sign to make GHOST hot cocoa",
    blurb: "The first spell of the season is a warm one.",
    how: "Make hot cocoa with milk, cocoa, sugar and a little vanilla. Draw a ghost face on a big marshmallow with an edible marker and float it on top.",
    source: "midgetmomma.com",
    img: "img/meals/01.jpg?v=2",
    recipe: "https://www.midgetmomma.com/halloween-hot-chocolate/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 2, date: "Fri 2 Oct", title: "Mummy Hot Dogs", emoji: "🌭",
    type: "snack", vibe: "cute",
    hook: "wait for the mummies to wake up",
    blurb: "They were very well behaved in the oven. Mostly.",
    how: "Cut crescent dough into thin strips and wrap them around hot dogs, leaving a gap for the face. Bake at 375°F / 190°C for 10–12 minutes. Add two capers as eyes.",
    source: "thekitchn.com",
    img: "img/meals/02.jpg?v=2",
    recipe: "https://www.thekitchn.com/mummy-hot-dogs-263652",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 3, date: "Sat 3 Oct", title: "Spiderweb Deviled Eggs", emoji: "🥚",
    type: "snack", vibe: "cute",
    hook: "peel this egg with me",
    blurb: "Peeling these is the most satisfying thing you'll do all week.",
    how: "Hard-boil eggs, gently crack the shells all over, soak the unpeeled eggs in water with blue food colouring, then peel to reveal the web. Fill with mashed yolk, mayo and mustard; top with black sesame seeds.",
    source: "egglandsbest.com",
    img: "img/meals/03.jpg?v=2",
    recipe: "https://www.egglandsbest.com/recipes/spooky-spiderweb-deviled-eggs",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 4, date: "Sun 4 Oct", title: "Jack-o'-Lantern Stuffed Peppers", emoji: "🫑",
    type: "dinner", vibe: "cozy",
    hook: "dinner, but make it jack-o'-lantern",
    blurb: "The easiest way to get anyone to eat their vegetables.",
    how: "Carve faces into orange peppers. Fill with cooked macaroni, lean beef, fire-roasted tomatoes and sharp cheddar. Bake at 350°F / 175°C for about 30 minutes.",
    source: "foodnetwork.com",
    img: "img/meals/04.jpg?v=2",
    recipe: "https://www.foodnetwork.com/recipes/trisha-yearwood/jack-o-lantern-stuffed-peppers-3893607",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 5, date: "Mon 5 Oct", title: "Witch Finger Breadsticks", emoji: "🤞",
    type: "snack", vibe: "gross",
    hook: "these breadsticks wave back",
    blurb: "Yes, they wave back.",
    how: "Tint bread dough green, roll into finger shapes, press in knuckle lines and an almond fingernail, sprinkle with cheese and bake. Serve with marinara.",
    source: "tasteofhome.com",
    img: "img/meals/05.jpg?v=2",
    recipe: "https://www.tasteofhome.com/recipes/witch-s-hairy-finger-breadsticks/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 6, date: "Tue 6 Oct", title: "Antipasto Eyeballs", emoji: "👁️",
    type: "snack", vibe: "gross",
    hook: "POV: your appetizer is watching you",
    blurb: "No-cook, 20 minutes, and deeply unsettling.",
    how: "Soften small mozzarella balls in hot water, shape two into one smooth ball, press a pimento-stuffed olive into the centre, wrap with a strip of prosciutto and skewer. No cooking.",
    source: "williams-sonoma.com",
    img: "img/meals/06.jpg?v=2",
    recipe: "https://www.williams-sonoma.com/recipe/halloween-antipasto-eyeballs.html",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 7, date: "Wed 7 Oct", title: "Graveyard Dirt Cups", emoji: "🪦",
    type: "dessert", vibe: "cute",
    hook: "something is buried in this pudding",
    blurb: "The kids' table favourite, every single year.",
    how: "Layer chocolate pudding and whipped topping with crushed Oreos in clear cups. Just before serving, add a cookie tombstone and gummy worms.",
    source: "glorioustreats.com",
    img: "img/meals/07.jpg?v=2",
    recipe: "https://www.glorioustreats.com/halloween-graveyard-dirt-cups/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 8, date: "Thu 8 Oct", title: "Witch Hat Cookies", emoji: "🎩",
    type: "dessert", vibe: "cute",
    hook: "I shrank my hat into a cookie",
    blurb: "Matching hats for the whole coven.",
    how: "Turn fudge-striped cookies upside down, pipe a ring of orange icing, and press a chocolate kiss into the centre. About 30 minutes, beginner-friendly.",
    source: "hersheyland.com",
    img: "img/meals/08.jpg?v=2",
    recipe: "https://www.hersheyland.com/recipes/kisses-witchs-hat-cookies.html",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 9, date: "Fri 9 Oct", title: "Spiderweb Cookies", emoji: "🕸️",
    type: "dessert", vibe: "cute",
    hook: "the stretchiest Halloween cookie",
    blurb: "Messy fingers, perfect webs.",
    how: "Bake chocolate oat cookies. Melt marshmallows and drizzle them over the cookies with a spoon to make webs. Add a candy spider.",
    source: "myfussyeater.com",
    img: "img/meals/09.jpg?v=2",
    recipe: "https://www.myfussyeater.com/chocolate-spider-web-cookies/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 10, date: "Sat 10 Oct", title: "Feetloaf", emoji: "🦶",
    type: "dinner", vibe: "gross",
    hook: "would you eat this?",
    blurb: "Gross? Yes. Delicious? Also yes.",
    how: "Shape your meatloaf mixture into two feet, press in onion slices as toenails, bake, then glaze with ketchup.",
    source: "tasty.co",
    img: "img/meals/10.jpg?v=2",
    recipe: "https://tasty.co/recipe/halloween-feet-loaf",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 11, date: "Sun 11 Oct", title: "Witches' Brew Punch", emoji: "🧪",
    type: "drink", vibe: "cute",
    hook: "something's in the punch...",
    blurb: "Kid-friendly, a handful of ingredients, maximum drama.",
    how: "Mix ginger ale, pineapple juice and fresh lime juice, then add scoops of lime sherbet and gummy worms. For the hand, freeze water in a new, clean food-safe glove.",
    source: "budgetbytes.com",
    img: "img/meals/11.jpg?v=2",
    recipe: "https://www.budgetbytes.com/witches-brew-halloween-punch/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 12, date: "Mon 12 Oct", title: "Mummy Pizza Bagels", emoji: "🍕",
    type: "dinner", vibe: "cute",
    hook: "pizza night, mummy edition",
    blurb: "Ten minutes, zero complaints.",
    how: "Spread pizza sauce on mini bagel halves, lay thin strips of string cheese across like bandages, add two black olive slices as eyes, and bake until melty.",
    source: "justataste.com",
    img: "img/meals/12.jpg?v=2",
    recipe: "https://www.justataste.com/mini-bagel-mummy-pizzas-recipe/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 13, date: "Tue 13 Oct", title: "Pretzel Rod Mummies", emoji: "🥨",
    type: "dessert", vibe: "cute",
    hook: "the easiest Halloween treat ever",
    blurb: "Kids can make these start to finish.",
    how: "Dip pretzel rods in melted white chocolate, drizzle more on in zig-zags for bandages, and add candy eyes before it sets.",
    source: "dinnersdishesanddesserts.com",
    img: "img/meals/13.jpg?v=2",
    recipe: "https://dinnersdishesanddesserts.com/mummy-pretzels/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 14, date: "Wed 14 Oct", title: "Brain Dip", emoji: "🧠",
    type: "snack", vibe: "gross",
    hook: "this dip is a no-brainer",
    blurb: "Your guests will stare. Then they'll eat all of it.",
    how: "Blend Boursin and cream cheese, press into a brain-shaped mould, chill until firm, turn out and drizzle with red pepper jelly.",
    source: "alekasgettogether.com",
    img: "img/meals/14.jpg?v=2",
    recipe: "https://alekasgettogether.com/halloween-brain-dip/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 15, date: "Thu 15 Oct", title: "Jack-o'-Lantern Quesadillas", emoji: "🧀",
    type: "dinner", vibe: "cozy",
    hook: "carve your quesadilla",
    blurb: "A five-minute weeknight save.",
    how: "Cut a jack-o'-lantern face out of one tortilla. Layer cheddar on a second tortilla, place the carved one on top, and toast in a pan until the cheese melts.",
    source: "weelicious.com",
    img: "img/meals/15.jpg?v=2",
    recipe: "https://weelicious.com/easy-jack-o-lantern-quesadillas/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 16, date: "Fri 16 Oct", title: "Banana Ghost Pops", emoji: "🍌",
    type: "dessert", vibe: "cute",
    hook: "boo-nanas!",
    blurb: "The healthy-ish one. You're welcome.",
    how: "Halve bananas, push in sticks and freeze. Dip in melted white chocolate, add mini chocolate chips for the faces, then freeze again.",
    source: "skinnytaste.com",
    img: "img/meals/16.jpg?v=2",
    recipe: "https://www.skinnytaste.com/frozen-boo-nana-pops/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 17, date: "Sat 17 Oct", title: "Skeleton Veggie Tray", emoji: "💀",
    type: "board", vibe: "cute",
    hook: "make veggies spooky and they vanish",
    blurb: "Save this for your party platter.",
    how: "Lay vegetables out as a skeleton on a large board: a bowl of ranch dip for the skull, celery and cucumber for bones, pepper strips for ribs, cauliflower for hands and feet.",
    source: "thishealthytable.com",
    img: "img/meals/17.jpg?v=2",
    recipe: "https://thishealthytable.com/blog/veggie-skeleton/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 18, date: "Sun 18 Oct", title: "Bat Wings", emoji: "🦇",
    type: "dinner", vibe: "gross",
    hook: "bat wings for dinner",
    blurb: "Sticky, dark, a little bit dangerous.",
    how: "Marinate wings in soy sauce, hoisin, a little fish sauce and a few drops of black gel food colouring, then roast until dark and sticky. Spread them open like bat wings to serve.",
    source: "simply-delicious-food.com",
    img: "img/meals/18.jpg?v=2",
    recipe: "https://simply-delicious-food.com/chicken-bat-wings-halloween/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 19, date: "Mon 19 Oct", title: "Poison Apples", emoji: "🍎",
    type: "dessert", vibe: "cozy",
    hook: "one bite... if you dare",
    blurb: "Every good witch needs a poison apple. (It's just caramel.)",
    how: "Make a caramel tinted black with gel food colouring, dip apples on sticks, and let them set on parchment.",
    source: "therecipecritic.com",
    img: "img/meals/19.jpg?v=2",
    recipe: "https://therecipecritic.com/poison-apples/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 20, date: "Tue 20 Oct", title: "Mummy Brownies", emoji: "🍫",
    type: "dessert", vibe: "cute",
    hook: "brownies that stare back",
    blurb: "The best thing you can do with a boxed mix.",
    how: "Bake a brownie mix, cool and cut into bars, pipe white frosting back and forth like bandages, and add candy eyes.",
    source: "bettycrocker.com",
    img: "img/meals/20.jpg?v=2",
    recipe: "https://www.bettycrocker.com/recipes/mummy-brownies/fe764df5-0563-493f-af62-689d44b80ac3",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 21, date: "Wed 21 Oct", title: "Witch Finger Cookies", emoji: "🍪",
    type: "dessert", vibe: "gross",
    hook: "don't bite your nails...",
    blurb: "The creepiest cookie on the tray.",
    how: "Roll shortbread dough into fingers, press in knuckle lines and a sliced-almond fingernail, bake, then dip the other end in warm raspberry jam.",
    source: "foodnetwork.com",
    img: "img/meals/21.jpg?v=2",
    recipe: "https://www.foodnetwork.com/recipes/giada-de-laurentiis/witch-finger-cookies-2229436",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 22, date: "Thu 22 Oct", title: "Spiderweb Pizza", emoji: "🕷️",
    type: "dinner", vibe: "cute",
    hook: "there's a spider on my pizza",
    blurb: "Pizza night, witch style.",
    how: "Cover the pizza base with sauce and cheddar, lay thin strips of string cheese in a web from the edge inward, add black olive spiders, and bake.",
    source: "sarahscoop.com",
    img: "img/meals/22.jpg?v=2",
    recipe: "https://sarahscoop.com/halloween-spiderweb-pizza-recipe/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 23, date: "Fri 23 Oct", title: "Mashed Potato Ghosts", emoji: "🥔",
    type: "dinner", vibe: "cute",
    hook: "ghosts for dinner",
    blurb: "The side dish that steals the show.",
    how: "Make mashed potatoes with russets, cream, butter and parmesan. Pipe into ghost shapes, add peppercorn eyes, and bake at 375°F / 190°C until the tips turn golden.",
    source: "eazypeazymealz.com",
    img: "img/meals/23.jpg?v=2",
    recipe: "https://www.eazypeazymealz.com/halloween-mashed-potato-ghosts/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 24, date: "Sat 24 Oct", title: "Mummy Jalapeño Poppers", emoji: "🌶️",
    type: "snack", vibe: "gross",
    hook: "spicy little mummies",
    blurb: "For the grown-ups' table.",
    how: "Fill jalapeño halves with cream cheese, wrap in thin strips of dough, bake until golden, and add candy eyes.",
    source: "skinnytaste.com",
    img: "img/meals/24.jpg?v=2",
    recipe: "https://www.skinnytaste.com/mummy-jalapeno-poppers/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 25, date: "Sun 25 Oct", title: "Halloween Charcuterie Board", emoji: "🍇",
    type: "board", vibe: "cozy",
    hook: "build a spooky board with me",
    blurb: "The board that does the decorating for you.",
    how: "Build a board of black and orange foods: cheddar, salami, black crackers, purple grapes, white-chocolate-dipped pretzel bones, and a Brie with a balsamic-glaze spiderweb.",
    source: "foodnetwork.com",
    img: "img/meals/25.jpg?v=2",
    recipe: "https://www.foodnetwork.com/recipes/food-network-kitchen/halloween-charcuterie-board-19770739",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 26, date: "Mon 26 Oct", title: "Pumpkin Cheese Ball", emoji: "🎃",
    type: "snack", vibe: "cozy",
    hook: "this pumpkin is made of cheese",
    blurb: "Five minutes, looks like hours.",
    how: "Mix cream cheese and shredded cheddar, shape into a ball, chill, roll in crushed cheese crackers, press in ridges, and add a pepper stem.",
    source: "dinneratthezoo.com",
    img: "img/meals/26.jpg?v=2",
    recipe: "https://www.dinneratthezoo.com/pumpkin-cheese-ball/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 27, date: "Tue 27 Oct", title: "Frankenstein Treats", emoji: "⚡",
    type: "dessert", vibe: "cute",
    hook: "IT'S ALIVE",
    blurb: "My favourite little monsters.",
    how: "Make rice cereal treats tinted green, cut into bars, top with melted chocolate almond bark for hair, add candy eyes, pipe stitches, and stick on mini marshmallows as bolts.",
    source: "butteryourbiscuit.com",
    img: "img/meals/27.jpg?v=2",
    recipe: "https://butteryourbiscuit.com/frankenstein-rice-krispie-treats/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 28, date: "Wed 28 Oct", title: "Witches' Brew Cider", emoji: "🍎",
    type: "drink", vibe: "cozy",
    hook: "don't mind the apple heads",
    blurb: "Pour one, sit by the fire, stay in tonight.",
    how: "Simmer apple cider with cinnamon sticks and orange slices. Peel apples, carve faces with a paring knife, and float them in the cider.",
    source: "mightymrs.com",
    img: "img/meals/28.jpg?v=2",
    recipe: "https://www.mightymrs.com/witch-brewed-cider-with-apple-heads/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 29, date: "Thu 29 Oct", title: "Graveyard Taco Dip", emoji: "🌮",
    type: "snack", vibe: "cute",
    hook: "a graveyard you can eat",
    blurb: "The party dip everyone gathers round.",
    how: "Layer beans, taco-seasoned beef, guacamole, cheddar and chopped veg. Write RIP on crackers with black gel icing and stand them in the dip as tombstones.",
    source: "avocadosfrommexico.com",
    img: "img/meals/29.jpg?v=2",
    recipe: "https://avocadosfrommexico.com/recipe/guacamole/haunted-graveyard-taco-dip/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 30, date: "Fri 30 Oct", title: "Soup in a Pumpkin", emoji: "🍲",
    type: "dinner", vibe: "cozy",
    hook: "dinner is inside this pumpkin",
    blurb: "The coziest centrepiece of the season.",
    how: "Hollow a pumpkin, fill it with Italian sausage, kale, cheese and broth, and bake it whole. Scoop out soft pumpkin with each serving.",
    source: "favfamilyrecipes.com",
    img: "img/meals/30.jpg?v=2",
    recipe: "https://www.favfamilyrecipes.com/soup-in-a-pumpkin/",
    instagram: "", youtube: "", facebook: ""
  },
  {
    night: 31, date: "Sat 31 Oct", title: "Ghost Cupcakes", emoji: "🧁",
    type: "dessert", vibe: "cute",
    hook: "Happy Halloween from Emma",
    blurb: "Happy Halloween! Thank you for cooking with me all month.",
    how: "Frost cupcakes with chocolate frosting. Drape a circle of white fondant over a lollipop to make each ghost, dot on eyes with black gel, and stand one on each cupcake.",
    source: "onceuponachef.com",
    img: "img/meals/31.jpg?v=2",
    recipe: "https://www.onceuponachef.com/recipes/ghost-cupcakes.html",
    instagram: "", youtube: "", facebook: ""
  }
];
