window.CR_REVIEWS = [
  {
    "id": 1,
    "stars": 5,
    "offer": "audit",
    "region": "Australia",
    "industry": "SaaS",
    "role": "Head of Engineering",
    "name": "Priya M.",
    "title": "Go/no-go before the cutover",
    "quote": "The two-week audit named the three paths that would have failed in production. We postponed one release and shipped the other with a written risk map instead of a gut call."
  },
  {
    "id": 2,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Cybersecurity",
    "role": "VP Engineering",
    "name": "Daniel K.",
    "title": "A named engineer in the sprint",
    "quote": "We did not get a ticket dump. We got one engineer on Slack, overlap hours that matched Pacific time, and a weekly risk note the product owner actually read."
  },
  {
    "id": 3,
    "stars": 5,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "Fintech",
    "role": "CTO",
    "name": "Amelia R.",
    "title": "Release readiness, not a slide deck",
    "quote": "The audit output was a gap list, a smoke pack, and a go/no-go. That is what we needed the week before a payment-rail change."
  },
  {
    "id": 4,
    "stars": 4,
    "offer": "seat",
    "region": "Australia",
    "industry": "Healthtech",
    "role": "QA Lead",
    "name": "Noah T.",
    "title": "Steady coverage on a thin team",
    "quote": "Seat replaced a contractor who had gone quiet. Onboarding was short. Replacement SLA was unused, which is the point."
  },
  {
    "id": 5,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "SaaS",
    "role": "Founder",
    "name": "Sofia L.",
    "title": "API regressions caught early",
    "quote": "Contract tests and a small Postman suite stopped the weekly \u2018it works in staging\u2019 surprise. Weekly written risk beat a status meeting."
  },
  {
    "id": 6,
    "stars": 5,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "Cybersecurity",
    "role": "Director of Product",
    "name": "James P.",
    "title": "What would break on Friday",
    "quote": "They mapped auth, tenancy, and the one job that only ran in prod. We fixed that job before customers saw it."
  },
  {
    "id": 7,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "Marketplace",
    "role": "Engineering Manager",
    "name": "Harpreet S.",
    "title": "Overlap hours that were real",
    "quote": "Delhi seat, Sydney stand-up. Daily window was agreed in writing. No 2 a.m. calls."
  },
  {
    "id": 8,
    "stars": 4,
    "offer": "audit",
    "region": "United States",
    "industry": "SaaS",
    "role": "Staff Engineer",
    "name": "Maya C.",
    "title": "Honest about scope",
    "quote": "Two weeks is two weeks. They did not pretend to rewrite the test strategy. They told us what was unsafe to ship."
  },
  {
    "id": 9,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "B2B SaaS",
    "role": "COO",
    "name": "Oliver W.",
    "title": "Weekly risk, not theatre",
    "quote": "One page every Friday: open risks, what we blocked, what can ship. Board stopped asking \u2018are we tested?\u2019"
  },
  {
    "id": 10,
    "stars": 5,
    "offer": "audit",
    "region": "Oman",
    "industry": "Public platform",
    "role": "Product Owner",
    "name": "Layla A.",
    "title": "Dynamic flows, not canned scripts",
    "quote": "Questions changed at runtime. Manual, API, and load tests had to compute the right answer on the fly. That was the actual product."
  },
  {
    "id": 11,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Devtools",
    "role": "Head of Quality",
    "name": "Chris B.",
    "title": "Automation that survived a refactor",
    "quote": "Framework was small on purpose. After a UI rewrite we still had the API layer. That was the useful part."
  },
  {
    "id": 12,
    "stars": 4,
    "offer": "seat",
    "region": "Australia",
    "industry": "Edtech",
    "role": "CTO",
    "name": "Isla G.",
    "title": "48-hour replacement, unused",
    "quote": "We asked about swap risk before signing. SLA is in the contract. We never needed it in the first quarter."
  },
  {
    "id": 13,
    "stars": 5,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "Insurtech",
    "role": "VP Product",
    "name": "Hannah D.",
    "title": "Performance before the campaign",
    "quote": "JMeter scenarios matched the real funnel, not a single GET. We raised the instance size before ads went live."
  },
  {
    "id": 14,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Healthcare SaaS",
    "role": "Engineering Lead",
    "name": "Rohit V.",
    "title": "Database checks in the sprint",
    "quote": "They treated data integrity as a release gate, not an afterthought. Two migration bugs never reached clinic staff."
  },
  {
    "id": 15,
    "stars": 5,
    "offer": "audit",
    "region": "Australia",
    "industry": "Cybersecurity",
    "role": "CISO (product)",
    "name": "Elena F.",
    "title": "Tenant isolation on the list",
    "quote": "Audit put cross-tenant access on page one. That is the review we needed, not a generic ISTQB checklist."
  },
  {
    "id": 16,
    "stars": 4,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "SaaS",
    "role": "Founder",
    "name": "Tom H.",
    "title": "Named person, not a bench",
    "quote": "We knew the engineer\u2019s name before week one. That alone was different from the last vendor."
  },
  {
    "id": 17,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Payments",
    "role": "Director of Engineering",
    "name": "Aisha N.",
    "title": "Regression pack we could run",
    "quote": "Smoke set ran in CI. We stopped doing a six-hour manual pass the night before release."
  },
  {
    "id": 18,
    "stars": 5,
    "offer": "audit",
    "region": "Australia",
    "industry": "Logistics SaaS",
    "role": "Head of Product",
    "name": "Ben J.",
    "title": "Integrations were the risk",
    "quote": "The product was fine. The carrier APIs were not. Audit spent the time where outages actually start."
  },
  {
    "id": 19,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "Cybersecurity",
    "role": "Staff QA",
    "name": "Freya L.",
    "title": "Security product, not a supermarket QA shop",
    "quote": "They did not pitch six equal services. Seat sat in the sprint and owned release risk for our console."
  },
  {
    "id": 20,
    "stars": 4,
    "offer": "audit",
    "region": "United States",
    "industry": "B2B SaaS",
    "role": "Product Manager",
    "name": "Kevin O.",
    "title": "Tight two weeks",
    "quote": "Fixed scope, fixed price. We got the risk map. We did not get a rewrite of the backlog, which some of us wanted."
  },
  {
    "id": 21,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "HR tech",
    "role": "VP Engineering",
    "name": "Sana Q.",
    "title": "NDA first, then access",
    "quote": "Process was dull in the good way. NDA, access, overlap hours, first risk note in week one."
  },
  {
    "id": 22,
    "stars": 5,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "Media SaaS",
    "role": "CTO",
    "name": "George M.",
    "title": "Flaky tests called out",
    "quote": "They marked the suite we trusted as untrustworthy. Awkward. Correct."
  },
  {
    "id": 23,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "SaaS",
    "role": "CEO",
    "name": "Nina S.",
    "title": "Cost that matched a seat",
    "quote": "From $600/month was the number we needed to try. We kept the seat after the first month because the Friday note was useful."
  },
  {
    "id": 24,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "Proptech",
    "role": "Tech Lead",
    "name": "Liam C.",
    "title": "Mobile + API together",
    "quote": "App store build and the billing API were tested as one path. That is how customers use it."
  },
  {
    "id": 25,
    "stars": 4,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "Healthtech",
    "role": "Head of Engineering",
    "name": "Chloe B.",
    "title": "Compliance adjacent, not a HIPAA stamp",
    "quote": "They did not sell a certification. They listed what would fail an audit of the release process."
  },
  {
    "id": 26,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Cybersecurity",
    "role": "Founding Engineer",
    "name": "Marcus E.",
    "title": "Load on the scanner path",
    "quote": "Performance work targeted the job customers wait on. Not the marketing site."
  },
  {
    "id": 27,
    "stars": 5,
    "offer": "audit",
    "region": "Australia",
    "industry": "Fintech",
    "role": "Risk & Product",
    "name": "Ananya P.",
    "title": "Go/no-go we could defend",
    "quote": "Recommendation was written. We showed it to the board. That was the deliverable."
  },
  {
    "id": 28,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "Marketplace",
    "role": "Engineering Manager",
    "name": "Callum R.",
    "title": "Replaced inside the SLA once",
    "quote": "First engineer was not a fit for the stack. Swap happened inside 48 hours. Second engineer stayed."
  },
  {
    "id": 29,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Analytics SaaS",
    "role": "Director of QA",
    "name": "Jennifer A.",
    "title": "SQL checks on the warehouse path",
    "quote": "Dashboard numbers were wrong twice in staging. Database QA caught the grain mismatch before the customer QBR."
  },
  {
    "id": 30,
    "stars": 4,
    "offer": "audit",
    "region": "Australia",
    "industry": "SaaS",
    "role": "Founder",
    "name": "Jade W.",
    "title": "Told us not to automate yet",
    "quote": "They refused a Selenium rewrite. Product was still moving. Manual + API was the adult answer."
  },
  {
    "id": 31,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "Legal tech",
    "role": "CTO",
    "name": "Edward N.",
    "title": "Written English in the report",
    "quote": "Risk notes were readable by counsel. That sounds small. It is not."
  },
  {
    "id": 32,
    "stars": 5,
    "offer": "audit",
    "region": "United States",
    "industry": "IoT / SaaS",
    "role": "VP Engineering",
    "name": "Diego S.",
    "title": "Device + cloud as one release",
    "quote": "Firmware and the cloud API were treated as one cut. We had been testing them as two products."
  },
  {
    "id": 33,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "Cybersecurity",
    "role": "Product Lead",
    "name": "Mei L.",
    "title": "Alerting paths under test",
    "quote": "The product pages were green. The pager path was not. Seat put tests on the thing on-call cares about."
  },
  {
    "id": 34,
    "stars": 4,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "SaaS",
    "role": "Head of Customer Success",
    "name": "Rachel K.",
    "title": "Fewer \u2018works on my machine\u2019 tickets",
    "quote": "Support volume on new features dropped after the seat owned a smoke path for each launch."
  },
  {
    "id": 35,
    "stars": 5,
    "offer": "audit",
    "region": "United States",
    "industry": "Edtech",
    "role": "Engineering Director",
    "name": "Paul Y.",
    "title": "Exam-week load, not average load",
    "quote": "They asked when traffic actually spikes. We tested that week, not a Tuesday in July."
  },
  {
    "id": 36,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "B2B SaaS",
    "role": "Founder",
    "name": "Arjun D.",
    "title": "ISTQB was the floor, not the pitch",
    "quote": "Certification got them in the door. The weekly note kept them there."
  },
  {
    "id": 37,
    "stars": 5,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "Payments",
    "role": "Staff Engineer",
    "name": "Sophie T.",
    "title": "Idempotency on the list",
    "quote": "Retry behaviour on the charge API was the finding that paid for the audit."
  },
  {
    "id": 38,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "HR tech",
    "role": "VP Product",
    "name": "Lauren I.",
    "title": "Same engineer across two quarters",
    "quote": "Continuity mattered more than a larger bench. We kept the named seat."
  },
  {
    "id": 39,
    "stars": 4,
    "offer": "audit",
    "region": "Australia",
    "industry": "Marketplace",
    "role": "CTO",
    "name": "Hugh F.",
    "title": "No theatre metrics",
    "quote": "They did not invent a 99% coverage number. They listed untested money paths."
  },
  {
    "id": 40,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "Healthtech",
    "role": "Technical Founder",
    "name": "Yasmin H.",
    "title": "Clinic workflow, not just CRUD",
    "quote": "Testers walked the booking-to-note path the way a nurse does. Bugs were in the seams."
  },
  {
    "id": 41,
    "stars": 5,
    "offer": "audit",
    "region": "United States",
    "industry": "SaaS",
    "role": "Head of Platform",
    "name": "Brett Z.",
    "title": "CI was lying",
    "quote": "Green pipeline, red product. Audit showed which jobs were skipped and which were flaky."
  },
  {
    "id": 42,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "Fintech",
    "role": "Engineering Manager",
    "name": "Tahlia M.",
    "title": "Timezone window in the SOW",
    "quote": "Overlap hours were a clause, not a hope. Stand-ups stayed inside the agreed window."
  },
  {
    "id": 43,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "Cybersecurity",
    "role": "Director of Engineering",
    "name": "Andre P.",
    "title": "Role-based access under test",
    "quote": "Admin vs analyst vs tenant-admin. Those three roles were the product. Tests finally treated them that way."
  },
  {
    "id": 44,
    "stars": 4,
    "offer": "audit",
    "region": "United Kingdom",
    "industry": "SaaS",
    "role": "Product Lead",
    "name": "Imogen V.",
    "title": "We wanted more weeks",
    "quote": "Two weeks was enough to decide. It was not enough to fix everything. That was said up front."
  },
  {
    "id": 45,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "Govtech-adjacent",
    "role": "Delivery Lead",
    "name": "Samir K.",
    "title": "Accessible release notes",
    "quote": "Risk report went to engineers and to the non-technical sponsor. Both could act on it."
  },
  {
    "id": 46,
    "stars": 5,
    "offer": "audit",
    "region": "United States",
    "industry": "Marketplace",
    "role": "CTO",
    "name": "Rebecca U.",
    "title": "Checkout path first",
    "quote": "They ignored the blog. They tested pay, refund, and failed webhooks. Correct order."
  },
  {
    "id": 47,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "Devtools",
    "role": "Head of Engineering",
    "name": "Niall G.",
    "title": "CLI + cloud console",
    "quote": "Users flip between both. Tests did too. That removed a class of \u2018but the UI does it\u2019 bugs."
  },
  {
    "id": 48,
    "stars": 5,
    "offer": "seat",
    "region": "United States",
    "industry": "SaaS",
    "role": "Founder",
    "name": "Priyanka J.",
    "title": "Reply in one business day",
    "quote": "Sales process matched the site: NDA, one inbox, a decision. No seven-call theatre."
  },
  {
    "id": 49,
    "stars": 4,
    "offer": "audit",
    "region": "Australia",
    "industry": "Cybersecurity",
    "role": "VP Engineering",
    "name": "Todd R.",
    "title": "Scope discipline",
    "quote": "We kept trying to add pentest-shaped work. They kept the audit on release readiness. Right call."
  },
  {
    "id": 50,
    "stars": 5,
    "offer": "seat",
    "region": "United Kingdom",
    "industry": "Insurtech",
    "role": "QA Manager",
    "name": "Helen S.",
    "title": "Partner, not a body shop",
    "quote": "They said they are not an offshore supermarket. The seat behaved that way."
  },
  {
    "id": 51,
    "stars": 5,
    "offer": "audit",
    "region": "United States",
    "industry": "Healthtech",
    "role": "Clinical Product Owner",
    "name": "Grace E.",
    "title": "Patient-facing edge cases",
    "quote": "Audit spent time on partial saves and late lab results. That is where we get support tickets."
  },
  {
    "id": 52,
    "stars": 5,
    "offer": "seat",
    "region": "Australia",
    "industry": "SaaS",
    "role": "CTO",
    "name": "Will P.",
    "title": "Kept the seat after the trial month",
    "quote": "First month was a test of the working agreement. We renewed because the risk note changed what we shipped."
  }
];
